import type { PlanDocument, PartyDetails } from './plan-sketch-types';
const blankParty = (): PartyDetails => ({ name: '', relation: 'S/o', relativeName: '', age: '', occupation: '', address: '' });
const SOURCE_SAMPLE_TEMPLATES: any[] = [
  {
    id: 'sample-sircilla-house-572',
    title: 'B. SRINIVAS (Claimant) - House (572.00 Sq.Yds - H.No. 6-5-48/2, Sy.No. 508/B, Sircilla)',
    createdAt: '2026-09-15',
    updatedAt: '2026-09-15',
    property: {
      propertyType: 'House',
      areaSqYards: 572.00,
      areaSqMtrs: 478.24,
      surveyNo: '508/B',
      plotNo: '20',
      houseNo: '6-5-48/2',
      houseAuthority: 'Municipal Council House No.',
      nearHNo: 'bearing Municipal Council House No.6-5-48/2',
      locality: 'Vidyanagar/ Renukanagar',
      village: 'Sircilla',
      mandal: 'Sircilla',
      district: 'Rajanna Sircilla',
      house: {
        enabled: true,
        widthFeet: 28,
        lengthFeet: 41.85,
        widthRaw: "28'-0\"",
        lengthRaw: "41'-10\"",
        structureType: 'R.C.C. Building',
        roofType: 'R.C.C. Slab',
        plinthPrefix: 'R.C.C.',
        plinthAreaSqFt: 1172.00,
        plinthAreaSqYds: 130.22,
        showMeasurements: true,
        showSetbacks: true,
        setbackNorth: "12'-0\"",
        setbackSouth: "12'-0\"",
        setbackEast: "8'-0\"",
        setbackWest: "8'-0\"",
        houseAuthority: 'Municipal Council House No.',
      },
      locationTemplateType: 'bearing_and_plot',
    },
    executant: [{
      name: 'V. RAMA RAO',
      relation: 'S/o',
      relativeName: 'NARSINGA RAO',
      age: '54',
      occupation: 'BUSINESS',
      address: 'Vidyanagar, Sircilla',
    }],
    claimant: [{
      name: 'B. SRINIVAS',
      relation: 'S/o',
      relativeName: 'VENKATESHAM',
      age: '42',
      occupation: 'EMPLOYEE',
      address: 'Renukanagar, Sircilla',
    }],
    boundaries: {
      northBoundary: 'HOUSE OF OTHERS',
      northDim: { raw: "68'-0\"", normalized: 68, unit: 'Feet' },
      southBoundary: '33\'-0" WIDE ROAD',
      southDim: { raw: "68'-0\"", normalized: 68, unit: 'Feet' },
      eastBoundary: 'PLOT NO. 21',
      eastDim: { raw: "75'-9\"", normalized: 75.75, unit: 'Feet' },
      westBoundary: 'PLOT NO. 19',
      westDim: { raw: "75'-9\"", normalized: 75.75, unit: 'Feet' },
      roadWidth: '33\'-0"',
      roadSides: ['South'],
      cornerProperty: false,
      dimensionUnit: 'Feet',
      northRotation: 0,
      mapRotation: 0,
      textScale: 100,
    },
    witnesses: {
      witness1: 'T. Chandra Shekar, S/o Narayana, R/o Sircilla',
      witness2: 'G. Suresh Kumar, S/o Gopal, R/o Sircilla',
    },
  },
  {
    id: 'sample-sircilla-registration',
    title: 'MARUVADI SWARUPA (Claimant) - Open Place (272.25 Sq.Yds - Sy.No. 1376/B/3, Sircilla)',
    createdAt: '2026-09-12',
    updatedAt: '2026-09-12',
    property: {
      propertyType: 'Open Place',
      areaSqYards: 272.25,
      areaSqMtrs: 227.62,
      surveyNo: '1376/B/3',
      nearHNo: '3-64',
      locality: 'SC COLONY/ INDIRAMMA COLONY/CHANDRAMPET OTHER',
      village: 'Sircilla',
      mandal: 'Sircilla',
      district: 'Rajanna Sircilla',
    },
    executant: [{
      name: 'SAKALI LAXMI',
      relation: 'W/o',
      relativeName: 'YELLAIAH',
      age: '60',
      occupation: 'HOUSE HOLD',
      address: 'H.No.7-79/2, Kondapur v/o Mustabad Mandal',
    }],
    claimant: [{
      name: 'MARUVADI SWARUPA',
      relation: 'W/o',
      relativeName: 'BABU (D/O SAKALI YELLAIAH)',
      age: '39',
      occupation: 'PRVT.EMPLOYEE',
      address: 'H.No.11-40, Kishandaspet, Yellareddypet Proper & Mandal',
    }],
    boundaries: {
      northBoundary: 'NEIGHBOUR PROPERTY',
      northDim: { raw: "45'-0\"", normalized: 45, unit: 'Feet' },
      southBoundary: '30\'-0" WIDE ROAD',
      southDim: { raw: "45'-0\"", normalized: 45, unit: 'Feet' },
      eastBoundary: 'HOUSE OF OTHERS',
      eastDim: { raw: "54'-5\"", normalized: 54.45, unit: 'Feet' },
      westBoundary: 'OPEN LAND',
      westDim: { raw: "54'-5\"", normalized: 54.45, unit: 'Feet' },
      roadWidth: '30\'-0"',
      roadSides: ['South'],
      cornerProperty: false,
      dimensionUnit: 'Feet',
    },
    witnesses: {
      witness1: 'T. Chandra Shekar, S/o Narayana, R/o Sircilla',
      witness2: 'G. Suresh Kumar, S/o Gopal, R/o Mustabad',
    },
  },
  {
    id: 'sample-standard-plot',
    title: 'M. SRINIVASA RAO (Claimant) - Plot (200 Sq.Yds - Sy.No. 142/A, Kompally)',
    createdAt: '2026-09-11',
    updatedAt: '2026-09-11',
    property: {
      propertyType: 'Plot',
      areaSqYards: 200,
      areaSqMtrs: 167.225,
      surveyNo: '142/A',
      nearHNo: '4-88/2',
      locality: 'Sri Sai Enclave',
      village: 'Kompally',
      mandal: 'Quthbullapur',
      district: 'Medchal-Malkajgiri',
    },
    executant: [{
      name: 'K. RAMESH BABU',
      relation: 'S/o',
      relativeName: 'LATE K. VENKATAIAH',
      age: '52',
      occupation: 'BUSINESS',
      address: 'H.No. 1-2-34, Kompally, Quthbullapur Mandal, Medchal Dist.',
    }],
    claimant: [{
      name: 'M. SRINIVASA RAO',
      relation: 'S/o',
      relativeName: 'M. SATYANARAYANA',
      age: '44',
      occupation: 'PRIVATE EMPLOYEE',
      address: 'Plot No. 12, Sri Sai Nagar, Nizampet, Hyderabad.',
    }],
    boundaries: {
      northBoundary: 'PLOT NO. 15',
      northDim: { raw: "40'-0\"", normalized: 40, unit: 'Feet' },
      southBoundary: '30\'-0" WIDE ROAD',
      southDim: { raw: "40'-0\"", normalized: 40, unit: 'Feet' },
      eastBoundary: 'PLOT NO. 17',
      eastDim: { raw: "45'-0\"", normalized: 45, unit: 'Feet' },
      westBoundary: 'PLOT NO. 14',
      westDim: { raw: "45'-0\"", normalized: 45, unit: 'Feet' },
      roadWidth: '30\'-0"',
      roadSides: ['South'],
      cornerProperty: false,
      dimensionUnit: 'Feet',
    },
    witnesses: {
      witness1: 'T. Chandra Shekar, S/o Narayana, R/o Hyderabad',
      witness2: 'G. Suresh Kumar, S/o Gopal, R/o Secunderabad',
    },
  },
  {
    id: 'sample-corner-house',
    title: 'P. VENKAT RAMAN (Claimant) - Corner House (266.66 Sq.Yds - Sy.No. 315/2, Gachibowli)',
    createdAt: '2026-09-11',
    updatedAt: '2026-09-11',
    property: {
      propertyType: 'House',
      areaSqYards: 266.66,
      areaSqMtrs: 222.962,
      surveyNo: '315/2',
      nearHNo: '8-124/1',
      locality: 'Venkateshwara Colony',
      village: 'Gachibowli',
      mandal: 'Serilingampally',
      district: 'Rangareddy',
    },
    executant: [{
      name: 'V. ANURADHA',
      relation: 'W/o',
      relativeName: 'V. PRAKASH REDDY',
      age: '48',
      occupation: 'HOUSEWIFE',
      address: 'Flat 402, Sai Residency, Serilingampally, Rangareddy Dist.',
    }],
    claimant: [{
      name: 'P. VENKAT RAMAN',
      relation: 'S/o',
      relativeName: 'P. APPA RAO',
      age: '39',
      occupation: 'SOFTWARE ENGINEER',
      address: 'H.No. 3-45/9, Gachibowli, Hyderabad.',
    }],
    boundaries: {
      northBoundary: '40\'-0" WIDE ROAD',
      northDim: { raw: "40'-5\"", normalized: 40.417, unit: 'Feet' },
      southBoundary: 'HOUSE OF K. MOHAN',
      southDim: { raw: "40'-0\"", normalized: 40, unit: 'Feet' },
      eastBoundary: '30\'-0" WIDE ROAD',
      eastDim: { raw: "60'-0\"", normalized: 60, unit: 'Feet' },
      westBoundary: 'HOUSE OF L. SUDHAKAR',
      westDim: { raw: "60'-0\"", normalized: 60, unit: 'Feet' },
      roadWidth: '40\' & 30\'',
      roadSides: ['North', 'East'],
      cornerProperty: true,
      dimensionUnit: 'Feet',
    },
    witnesses: {
      witness1: 'N. Ravi Varma, S/o Subba Raju, R/o Hyderabad',
      witness2: 'B. Jagadish, S/o Krishna Murthy, R/o Hyderabad',
    },
  },
  {
    id: 'sample-open-place',
    title: 'SYED MOHAMMED ALI (Claimant) - Open Place (166.66 Sq.Yds - Sy.No. 89, Shamshabad)',
    createdAt: '2026-09-11',
    updatedAt: '2026-09-11',
    property: {
      propertyType: 'Open Place',
      areaSqYards: 166.66,
      areaSqMtrs: 139.349,
      surveyNo: '89',
      nearHNo: '2-12',
      locality: 'Balaji Nagar',
      village: 'Shamshabad',
      mandal: 'Rajendranagar',
      district: 'Rangareddy',
    },
    executant: [{
      name: 'D. SRINIVAS',
      relation: 'S/o',
      relativeName: 'D. MALLESHAM',
      age: '41',
      occupation: 'REAL ESTATE',
      address: 'Shamshabad Village & Mandal, Rangareddy Dist.',
    }],
    claimant: [{
      name: 'SYED MOHAMMED ALI',
      relation: 'S/o',
      relativeName: 'SYED HUSSAIN',
      age: '46',
      occupation: 'MERCHANT',
      address: 'H.No. 18-4-102, Charminar, Hyderabad.',
    }],
    boundaries: {
      northBoundary: 'OPEN LAND OF SRI J. RAO',
      northDim: { raw: "30'-0\"", normalized: 30, unit: 'Feet' },
      southBoundary: '33\'-0" WIDE ROAD',
      southDim: { raw: "30'-0\"", normalized: 30, unit: 'Feet' },
      eastBoundary: 'NEIGHBOUR PLOT',
      eastDim: { raw: "50'-0\"", normalized: 50, unit: 'Feet' },
      westBoundary: 'PLOT OF SMT. SARITHA',
      westDim: { raw: "50'-0\"", normalized: 50, unit: 'Feet' },
      roadWidth: '33\'-0"',
      roadSides: ['South'],
      cornerProperty: false,
      dimensionUnit: 'Feet',
    },
    witnesses: {
      witness1: 'Mohammed Saleem, S/o Ibrahim, R/o Hyderabad',
      witness2: 'K. Balakrishna, S/o Pochaiah, R/o Shamshabad',
    },
  },
];
export const SAMPLE_PLAN_TEMPLATES: PlanDocument[] = SOURCE_SAMPLE_TEMPLATES.map(sample => {
  const executants = Array.isArray(sample.executant) ? sample.executant : sample.executant ? [sample.executant] : [];
  const claimants = Array.isArray(sample.claimant) ? sample.claimant : sample.claimant ? [sample.claimant] : [];
  return { ...sample, executant: executants[0] || blankParty(), claimant: claimants[0] || blankParty(), executants, claimants };
});
